export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const EDIT_ITEM = 'EDIT_ITEM'
export const COMPLETE_ITEM = 'COMPLETE_ITEM' 
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const GET_DATA = 'GET_DATA'
